### ISSUE TITLE
New JyIDV install- Root problem?

### ISSUE THREAD

**Issue by bmatilla** [suvarchal/JyIDV#9]
After extracting the files from the Github into the appropriate directory, setup.py runs with no exceptions. However, this is the terminal error I receive when I try to launch the IDV kernel in the Notebook.

```
[I 13:50:15.685 NotebookApp] KernelRestarter: restarting kernel (4/5)
WARNING:root:kernel a7b2cb12-8e42-4879-8eaa-5eac70da7097 restarted
Traceback (most recent call last):
  File "/Users/Brian/anaconda/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Users/Brian/anaconda/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/Brian/anaconda/lib/python2.7/site-packages/jyidv_kernel.py", line 301, in <module>
    IPKernelApp.launch_instance(kernel_class=JythonKernel)
  File "/Users/Brian/anaconda/lib/python2.7/site-packages/traitlets/config/application.py", line 588, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-122>", line 2, in initialize
  File "/Users/Brian/anaconda/lib/python2.7/site-packages/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/Brian/anaconda/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 421, in initialize
    self.init_kernel()
  File "/Users/Brian/anaconda/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 360, in init_kernel
    user_ns=self.user_ns,
  File "/Users/Brian/anaconda/lib/python2.7/site-packages/traitlets/config/configurable.py", line 404, in instance
    inst = cls(*args, **kwargs)
  File "/Users/Brian/anaconda/lib/python2.7/site-packages/jyidv_kernel.py", line 30, in __init__
    self._start_jython()
  File "/Users/Brian/anaconda/lib/python2.7/site-packages/jyidv_kernel.py", line 59, in _start_jython
    raise Exception("IDV_HOME not found")
Exception: IDV_HOME not found
[W 13:50:18.698 NotebookApp] KernelRestarter: restart failed
[W 13:50:18.699 NotebookApp] Kernel a7b2cb12-8e42-4879-8eaa-5eac70da7097 died, removing from map.
ERROR:root:kernel a7b2cb12-8e42-4879-8eaa-5eac70da7097 restarted failed!
```

It may just be as simple as rerouting the IDV root directory but am not 100% sure if that's the way to go.

**Comment by brianmapes** [comment]
IDV_HOME not found

Read suvys instructions about setting that. If that step is too buried, make a suggestion including rewording instructions on the issues page of his github repo. Or fix it in your fork and make a pull request. Thanks for walking these formal trails. It's part of your career education.

Brian Mapes
This message was typed on a cell phone, please forgive its terseness and any errors.

On Jun 1, 2016, at 12:49 PM, bmatilla <notifications@github.com<mailto:notifications@github.com>> wrote:

IDV_HOME not found

**Comment by brianmapes** [comment]
If I recall IDVhome path has has the 5.x hardwired into it.
If you install the nightly 5.3u1, that name will last until 5.4.
Save you a confusion later.

Sent from my iPad

On Jun 1, 2016, at 12:49 PM, bmatilla <notifications@github.com<mailto:notifications@github.com>> wrote:

This is the terminal error I receive when I try to launch the IDV kernel in the Notebook.

[I 13:50:15.685 NotebookApp] KernelRestarter: restarting kernel (4/5)
WARNING:root:kernel a7b2cb12-8e42-4879-8eaa-5eac70da7097 restarted
Traceback (most recent call last):
  File "/Users/Brian/anaconda/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Users/Brian/anaconda/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/Brian/anaconda/lib/python2.7/site-packages/jyidv_kernel.py", line 301, in <module>
    IPKernelApp.launch_instance(kernel_class=JythonKernel)
  File "/Users/Brian/anaconda/lib/python2.7/site-packages/traitlets/config/application.py", line 588, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-122>", line 2, in initialize
  File "/Users/Brian/anaconda/lib/python2.7/site-packages/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, _args, *_kwargs)
  File "/Users/Brian/anaconda/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 421, in initialize
    self.init_kernel()
  File "/Users/Brian/anaconda/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 360, in init_kernel
    user_ns=self.user_ns,
  File "/Users/Brian/anaconda/lib/python2.7/site-packages/traitlets/config/configurable.py", line 404, in instance
    inst = cls(_args, *_kwargs)
  File "/Users/Brian/anaconda/lib/python2.7/site-packages/jyidv_kernel.py", line 30, in __init__
    self._start_jython()
  File "/Users/Brian/anaconda/lib/python2.7/site-packages/jyidv_kernel.py", line 59, in _start_jython
    raise Exception("IDV_HOME not found")
Exception: IDV_HOME not found
[W 13:50:18.698 NotebookApp] KernelRestarter: restart failed
[W 13:50:18.699 NotebookApp] Kernel a7b2cb12-8e42-4879-8eaa-5eac70da7097 died, removing from map.
ERROR:root:kernel a7b2cb12-8e42-4879-8eaa-5eac70da7097 restarted failed!

It may just be as simple as rerouting the IDV root directory but am not 100% sure if that's the way to go.

**Comment by suvarchal** [comment]
Export variable IDV_HOME /path/to/whereIDVis in your .bashrc or .cshrc ( and dont forget to source the bashrc or cshrc and check if it is right by using `echo $IDV_HOME`) and try again installing JyIDV, it is necessary you set IDV_HOME path before you install JyIDV. 
lets see if error comes up again.

**Comment by bmatilla** [comment]
Issue has been resolved. Thanks again!
